# Type stubs for essentia

from typing import Any, Callable, List
import numpy as np


class standard:
    class MonoLoader:
        def __init__(self, filename: str, sampleRate: int,
                     resampleQuality: int) -> None: ...

        def __call__(self) -> np.ndarray: ...

    class TensorflowPredictVGGish:
        def __init__(self, graphFilename: str, output: str) -> None: ...
        def __call__(self, audio: np.ndarray) -> np.ndarray: ...

    class TensorflowPredictEffnetDiscogs:
        def __init__(self, graphFilename: str, output: str) -> None: ...
        def __call__(self, audio: np.ndarray) -> np.ndarray: ...

    class TensorflowPredictMusiCNN:
        def __init__(self, graphFilename: str, output: str) -> None: ...
        def __call__(self, audio: np.ndarray) -> np.ndarray: ...

    class TensorflowPredict2D:
        def __init__(self, graphFilename: str, output: str) -> None: ...
        def __call__(self, embedding: np.ndarray) -> np.ndarray: ...
    
    class TensorflowPredictMAEST:
        def __init__(self, graphFilename: str, output: str) -> None: ...
        def __call__(self, audio: np.ndarray) -> np.ndarray: ...


def MonoLoader(filename: str, sampleRate: int,
               resampleQuality: int) -> Any: ...


def TensorflowPredictVGGish(graphFilename: str, output: str) -> Any: ...
def TensorflowPredictEffnetDiscogs(graphFilename: str, output: str) -> Any: ...
def TensorflowPredictMusiCNN(graphFilename: str, output: str) -> Any: ...
def TensorflowPredict2D(graphFilename: str, output: str) -> Any: ...
