/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type DaytimeSection = "afternoon" | "evening" | "morning" | "night";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Platform = "jamendo" | "local";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AbortRecLog {
  alternate_track_id: string | null;
  id: Generated<number>;
  original_track_id: string;
  reclog_id: number | null;
  timestamp: Generated<Timestamp>;
  user_id: string;
}

export interface ListenHistory {
  id: Generated<number>;
  timestamp: Generated<Timestamp>;
  track_id: string;
  user_id: string;
}

export interface ModelTrainingData {
  case_ids: number[];
  id: Generated<number>;
  model_id: number;
  timestamp: Generated<Timestamp>;
}

export interface PhysicalFeedback {
  baseline_id: number | null;
  daytime_section: DaytimeSection;
  gap_sec: number;
  id: Generated<number>;
  index_in_session: number;
  listen_end_sec: number;
  listen_start_sec: number;
  r_hf_ln: number;
  r_hr_literal: number;
  r_lf_ln: number;
  r_mental_status: string | null;
  r_pnn50_literal: number;
  r_rmssd_ln: number;
  r_sdnn_literal: number;
  reclog_id: number | null;
  session_id: string;
  t_hf_ln: number;
  t_hr_literal: number;
  t_lf_ln: number;
  t_mental_status: string | null;
  t_pnn50_literal: number;
  t_rmssd_ln: number;
  t_sdnn_literal: number;
  timestamp: Generated<Timestamp>;
  track_id: string;
  u_hf_ln: number;
  u_hr_literal: number;
  u_lf_ln: number;
  u_mental_status: string | null;
  u_pnn50_literal: number;
  u_rmssd_ln: number;
  u_sdnn_literal: number;
  user_id: string;
}

export interface RecommendationLog {
  candidate_track_ids: string[];
  id: Generated<number>;
  model_id: number | null;
  timestamp: Generated<Timestamp>;
  u_hrv_literal_at_request: Json;
  user_id: string;
}

export interface Track {
  created_at: Generated<Timestamp>;
  duration_s: number;
  hidden: Generated<boolean>;
  hidden_reason: string | null;
  id: string;
  name: string;
}

export interface TrackAudioFeatures {
  chroma_flux_mean: number;
  chroma_flux_skewness: number;
  chroma_flux_std: number;
  loud_mean: number;
  loud_skewness: number;
  loud_std: number;
  mode: number;
  pulse_clarity: number;
  tempo: number;
  tempo_std: number;
  thumbnail_chroma_flux_mean: number;
  thumbnail_chroma_flux_skewness: number;
  thumbnail_chroma_flux_std: number;
  thumbnail_coverage: number;
  thumbnail_end_sec: number;
  thumbnail_loud_mean: number;
  thumbnail_loud_skewness: number;
  thumbnail_loud_std: number;
  thumbnail_mode: number;
  thumbnail_pulse_clarity: number;
  thumbnail_score: number;
  thumbnail_start_sec: number;
  thumbnail_tempo: number;
  thumbnail_tempo_std: number;
  timestamp: Generated<Timestamp>;
  track_id: string;
}

export interface TrackFeatEnvelopes {
  env_chroma_flux: number[];
  env_chroma_matrix: number[][];
  env_loudness_db: number[];
  env_pulse_clarity: number[];
  env_tempo: number[];
  loud_chroma_sample_rate: number;
  timestamp: Generated<Timestamp>;
  track_id: string;
}

export interface TrackMetadata {
  acousticelectric: boolean | null;
  acoustid: string | null;
  artist_name: string | null;
  genres: Generated<string[]>;
  instruments: Generated<string[]>;
  mb_artist_id: string | null;
  mb_recording_id: string | null;
  tags_source: string | null;
  track_id: string;
  vartags: Generated<string[]>;
  vocalinstrumental: boolean | null;
}

export interface TrackPlatform {
  platform: Platform;
  platform_id: string;
  track_id: string;
}

export interface UserHrvBaseline {
  daytime_section: DaytimeSection;
  hf_literal: number;
  hf_std: number;
  hf_ln_mean: number | null;
  hf_ln_std: number | null;
  hr_literal: number;
  hr_std: number;
  id: Generated<number>;
  lf_literal: number;
  lf_std: number;
  lf_ln_mean: number | null;
  lf_ln_std: number | null;
  pnn50_literal: number;
  pnn50_std: number;
  rmssd_literal: number;
  rmssd_std: number;
  rmssd_ln_mean: number | null;
  rmssd_ln_std: number | null;
  sdnn_literal: number;
  sdnn_std: number;
  timestamp: Generated<Timestamp>;
  user_id: string | null;
}

export interface Users {
  created_at: Generated<Timestamp>;
  hidden: Generated<boolean>;
  hidden_reason: string | null;
  id: string;
  name: string;
}

export interface XgbModels {
  active: Generated<boolean>;
  id: Generated<number>;
  model_hf: Json;
  model_hr: Json;
  model_lf: Json;
  model_pnn50: Json;
  model_rmssd: Json;
  model_sdnn: Json;
  timestamp: Generated<Timestamp>;
  user_id: string | null;
}

export interface DB {
  abort_rec_log: AbortRecLog;
  listen_history: ListenHistory;
  model_training_data: ModelTrainingData;
  physical_feedback: PhysicalFeedback;
  recommendation_log: RecommendationLog;
  track: Track;
  track_audio_features: TrackAudioFeatures;
  track_feat_envelopes: TrackFeatEnvelopes;
  track_metadata: TrackMetadata;
  track_platform: TrackPlatform;
  user_hrv_baseline: UserHrvBaseline;
  users: Users;
  xgb_models: XgbModels;
}
