/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface EmbEffnetDiscogs400 {
  created_at: Generated<Timestamp>;
  embedding: number[];
  id: string;
}

export interface EmbMsdMusicnn {
  created_at: Generated<Timestamp>;
  embedding: number[];
  id: string;
}

export interface IdSha256 {
  id: string;
}

export interface VaEmomusicMsdMusicnn {
  arousal: number;
  created_at: Generated<Timestamp>;
  id: string;
  valence: number;
}

export interface DB {
  emb_effnet_discogs400: EmbEffnetDiscogs400;
  emb_msd_musicnn: EmbMsdMusicnn;
  id_sha256: IdSha256;
  va_emomusic_msd_musicnn: VaEmomusicMsdMusicnn;
}
