/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Mode = "major" | "minor";

export type Platform = "jamendo";

export type TempoCategory = "fast" | "moderate" | "slow";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BaseAudioFeatures {
  chroma_flux: number[];
  chroma_matrix: number[][];
  len: number;
  loudness_db: number[];
  sr_hz: number;
  timestamp: Generated<Timestamp>;
  track_id: string;
}

export interface ListenHistory {
  timestamp: Generated<Timestamp>;
  track_id: string;
  user_id: string;
}

export interface Track {
  duration_s: number;
  id: string;
  name: string;
}

export interface TrackGlobalRisks {
  dynamic_range_db: number;
  f0_range_hz: number;
  mean_f0_hz: number;
  mean_loudness_db: number;
  mode: Mode;
  mode_score: number;
  pulse_clarity: number;
  tempo_bpm: number;
  tempo_category: TempoCategory;
  tempo_score: number;
  track_id: string;
}

export interface TrackHrvEffPredict {
  hr: number;
  lfhf: number;
  rmssd: number;
  timestamp: Generated<Timestamp>;
  track_id: string;
}

export interface TrackPlatform {
  platform: Platform;
  platform_id: string;
  track_id: string;
}

export interface TrackPredictionsMeta {
  f0_envelope_mean_hz: number;
  f0_midi_mean: number;
  f0_midi_std: number;
  f0_midi_variance: number;
  global_confidence: number;
  loudness_envelope_mean: number;
  loudness_stability: number;
  mode_mean: number;
  music_envelope_mean: number;
  music_envelope_std: number;
  pulse_clarity_mean: number;
  smoothness: Json;
  tempo_mean_bpm: number;
  thumbnail_duration: number;
  thumbnail_end: number;
  thumbnail_start: number;
  track_id: string;
}

export interface TrackValidationArrays {
  array_length: number;
  f0_envelope_hz_4hz: number[];
  loudness_envelope_4hz: number[];
  music_envelope_4hz: number[];
  sampling_rate_hz: number;
  track_id: string;
}

export interface Users {
  id: string;
  name: string;
}

export interface DB {
  base_audio_features: BaseAudioFeatures;
  listen_history: ListenHistory;
  track: Track;
  track_global_risks: TrackGlobalRisks;
  track_hrv_eff_predict: TrackHrvEffPredict;
  track_platform: TrackPlatform;
  track_predictions_meta: TrackPredictionsMeta;
  track_validation_arrays: TrackValidationArrays;
  users: Users;
}
