from typing import Any
import numpy as np


class MonoLoader:
    def __init__(self, filename: str, sampleRate: int,
                 resampleQuality: int) -> None: ...

    def __call__(self) -> np.ndarray: ...


class TensorflowPredictVGGish:
    def __init__(self, graphFilename: str, output: str) -> None: ...
    def __call__(self, audio: np.ndarray) -> np.ndarray: ...


class TensorflowPredictEffnetDiscogs:
    def __init__(self, graphFilename: str, output: str) -> None: ...
    def __call__(self, audio: np.ndarray) -> np.ndarray: ...


class TensorflowPredictMusiCNN:
    def __init__(self, graphFilename: str, output: str) -> None: ...
    def __call__(self, audio: np.ndarray) -> np.ndarray: ...


class TensorflowPredict2D:
    def __init__(self, graphFilename: str, output: str) -> None: ...
    def __call__(self, embedding: np.ndarray) -> np.ndarray: ...
